version: "3.8"

services:

  main_frontend:
    image: main_frontend:latest
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend-api:
    platform: linux/amd64
    image: backend-api:latest
    build:
      context: ./backend
    volumes:
      - ./backend/api:/api #Only dev
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/simulators:/simulators
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload # dev only
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: test
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      PYTHON_ON_WHALES_DEBUG: 1
    ports:
      - "2000:80"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresqk/data
    volumes:
      - ./database-data:/var/lib/postgresql/data
    ports:
      - "6543:5432"
